### ISSUE TITLE
Animal Herder: Chicken

### ISSUE THREAD

**Issue by Kostronor** [Minecolonies/minecolonies#179]

**Comment by thejakegates** [comment]
Would it be possible instead of having a separate job for each animal to have a single job called Rancher and treat it the same way as the Farmer?  Use an item like a field called trough that would be set to the animal you want and then the higher the level the more pens each rancher could have. 

Just an idea I had while going through the code and trying to find something to tackle to use as for an application to join the team.

**Comment by Raycoms** [comment]
Hi @thejakegates, if you're interested in a task, try to contact me on our discord:
https://discord.gg/gA7T6ma

About the separate jobs. We were actually thinking about making it similar to the real farmer, but it considered it more interesting in terms of city planning having 1 each.
Also since we want to avoid too many animals.
If we'd make it like the normal farmer, we'd have over 100 animals really rapidly.
(2-3 Animal farmers level 5 would cause that already). Which would cause lags on a lot of servers.

**Comment by Raycoms** [comment]
Additionally, @Asherslab is already pretty close with this =D

**Comment by thejakegates** [comment]
I'll definitely get on discord, thanks!

I see where you're coming from with the one each, just wanted to throw the idea out in case it wasn't discussed.

**Comment by Asherslab** [comment]
Okay. so my thoughts on this, would be that
A) Most certainly not Seperate "Fields" for each (Would be amazingly hard to balance, and Code, and honestly it would make the Herders very inefficient) (Sorry don't mean to be rude, just Aussie)
B) Putting them all into One block would be OKAY by me, but personally i like the idea of seperate herder types. because 
    1. It allows for different schematics for different herder types (Do you really look after chickens the same way as you do cows? Yes it'd be possible to allow different schemes for different jobs within the same hut, BUT then you'd have to A) Rebuild the hut every time. and B) Well let's just say you'd have a fun time removing the old animals, and putting new ones in...
    2. It's a lot nicer for building colonies!
    3. It'd be the same as with the Ranger and Knight, you'd have to hire/fire or kill the worker every time you wanted to switch and crap.

Anyway fun times. feel free to spam me with more worker ideas.

**Comment by Asherslab** [comment]
Done
