### ISSUE TITLE
Add extra info to citizens  [$5]

### ISSUE THREAD

**Issue by Kostronor** [Minecolonies/minecolonies#187]
Each citizen should have a text telling what they are up to human readable. 

Suggestion would be an overrideable method returning String[] 

Or later in the task interface 

[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=41624373)](https://www.bountysource.com/issues/41624373-add-extra-info-to-citizens?utm_source=41624373&utm_medium=shield&utm_campaign=ISSUE_BADGE)

**Comment by Asherslab** [comment]
I'm guessing this is talking about what you see with "enableDevelopmentFeatures" on with their "Current task" just after their name?

**Comment by Raycoms** [comment]
It's more like the command info

On Jul 31, 2017 07:25, "Asherslab" <notifications@github.com> wrote:

I'm guessing this is talking about what you see with
"enableDevelopmentFeatures" on with their "Current task" just after their
name?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/Minecolonies/minecolonies/issues/187#issuecomment-318970973>,
or mute the thread

**Comment by Raycoms** [comment]
That's a duplicate we have an issue for that already. With more discussion and more explanation
