### ISSUE TITLE
Lumberjack is not gathering saplings from his chest

### ISSUE THREAD

**Issue by Kostronor** [Minecolonies/minecolonies#247]
### Minecolonies version

1500
### Expected behavior

if no saplings around him are found but some are in his worker chest he should take them
### Actual behaviour

he runs aroung gathering even if his hut has some
### Steps to reproduce the problem

take all his saplings and put them in his hut

**Comment by Raycoms** [comment]
The lumberjack will now and then try to gather some saplings. That's no
bug. Even when I have some in my chests I also run around gathering them
when I go cutting wood.
We will use the saplings he deposits for some other purposes later on.
He will always keep at least 10, that's why that run out but have some in
his chest should never happen.

2016-10-30 10:34 GMT-02:00 Marvin Hofmann <notifications@github.com>:

**Comment by kyperitus** [comment]
He also sits and does absolutely nothing if a sapling does not fall for him, to reproduce this just break the leaves in creative before a sapling falls. He fixes himself upon you adding a sapling of the tree he just chopped to his inventory.

**Comment by Raycoms** [comment]
The last problem I fixed in the last update.
