### ISSUE TITLE
[1.10.2-0.4.1704] Interface won't open.

### ISSUE THREAD

**Issue by mainframecn** [Minecolonies/minecolonies#277]
### Minecolonies version

version 1.10.2-0.4.1704 

### Expected behavior

- Building/hut/citizen inventory/interface should open. 

### Actual behaviour

- It won't open. (Placing a tinkers construct crafting table next to an inventory lets me access inventory.)
  Unclear when it stops working, starting out it works after some time it just won't be accessible anymore. Restarts don't seems to solve the issue.

**Comment by Raycoms** [comment]
Are you an officer in that colony?

2016-11-12 9:49 GMT-02:00 mainframecn <notifications@github.com>:

**Comment by mainframecn** [comment]
Ah, excuse me. Should have included that info. It's a single player world and i'm the owner.
Also i just noticed the update to 0.4.1711, but this didn't fix it.

**Comment by mainframecn** [comment]
My log is filled with errors like these:

[Netty Local Client IO #0/ERROR] [minecolonies/]: Colony view does not exist for ID #1

**Comment by Raycoms** [comment]
Ah due to the update some of the older version seemed to start have
problems due to the additional permissions.
We're also still debugging this.
To fix that you'd unfortunately would have to reset your colony and start
new (Also possible in the same world at the same spot)

2016-11-12 9:58 GMT-02:00 mainframecn <notifications@github.com>:

**Comment by mainframecn** [comment]
I'm not sure how to reset the colony properly. Breaking the core blocks of the buildings doesn't seem to help.

**Comment by Raycoms** [comment]
It's a command it's  "/mc colony delete 1"

2016-11-12 10:05 GMT-02:00 mainframecn <notifications@github.com>:

**Comment by Raycoms** [comment]
I think your problem is a different one.
I guess due to some strange minecraft bugs your colony got deleted.
Restarting didn't resolve the problem?

**Comment by xenoflot** [comment]
I seem to be having this problem as well. I'm playing on a local server and I'm the only player. 
I created a colony and construction work was underway on my town hall. My client got the vanilla "stuck in bed" bug and I had to kill and restart the client.  After reconnecting to the server, I cannot interact with any of the MC NPCs nor the Builder & TownHall blocks.

However, my builder is happily working away if I drop the materials at her feet. She completed the work as I was typing this and I got the town hall achievement. That didn't help.

_/mc colonies list_ shows my colony and ownership as expected.

Restarting the server... *does* help. I was able to interact with the builder block and kick off an upgrade. I did _not_ restart my client again so the problem must be due to the server task getting upset because it lost communication with the client.

minecraft 1.10.2
minecolonies 1.10.2-0.4.1784
forge 2122
Full mod list: http://pastebin.com/m3K6ck9M

**Comment by Raycoms** [comment]
Now after restarting it does work again?
The problem is that due to such a crash, minecraft might corrupt our files
and permissions can't be completely loaded again.

2016-11-27 23:20 GMT-02:00 xenoflot <notifications@github.com>:

**Comment by xenoflot** [comment]
The client crashed but not the server.
After restarting the client, I had the problem.
Restarting the server fixed the problem.
If the corruption was client-side, something about restarting the server fixed it. Which seems a little odd. 

I'm _not_ an experienced programmer (I can't even figure out how to make forgegradle work!) but my guess would be that a message between client and server went missing in the crash, and the server got stuck in a state where it was waiting for a particular message from the client. Because the client had crashed, it didn't know that it needed to send the message.

No point me speculating any further. You know how it works, I don't :-)

Cheers!

**Comment by Raycoms** [comment]
Will have to keep looking. It seems like sometimes the minecolonies.nbt file gets into problems while restarting crashing etc. Probably won't be able to do anything against that or improving it (could write it into three files and proof them etc, but that would be a bit too much overhead for the amount of times it actually happens.)

**Comment by kotoroshinoto** [comment]
it happens to me continuously, so "amount of times it actually happens" seems to need reassessment.

**Comment by kotoroshinoto** [comment]
the longer the server is up, the more likely the colony is to derp itself and require a restart

**Comment by Raycoms** [comment]
There is a command now for that: "/mc colony refresh" which should solve
this.

2017-03-05 17:29 GMT-03:00 kotoroshinoto <notifications@github.com>:

**Comment by kotoroshinoto** [comment]
could you possibly include a way of acessing the function that can be run from the server command line input? (perhaps to refresh all colonies, or colonies for specific player, or a specific colony id?)

**Comment by kotoroshinoto** [comment]
right now it gets a classcast exception cannot be cast to entityplayer

**Comment by Raycoms** [comment]
can you give me the log?

then please do /mc colony info yourName (to get your colonyId) and then /mc
colony refresh id

2017-03-05 23:06 GMT-03:00 kotoroshinoto <notifications@github.com>:

**Comment by VOiDProXy** [comment]
I ran into this issue tonight, I succesfully regained access to my buildings by typing
`/mc colony refresh`
Thanks @Raycoms 

Edit: Aaaaand I just realized this issue was closed. Sorry, I am a GitHub noob

**Comment by Raycoms** [comment]
Glad it worked =)

**Comment by kotoroshinoto** [comment]
sorry I haven't supplied a log yet. I haven't been on when the errors have happened, i've only heard about it after the fact.
