### ISSUE TITLE
WOODEN SLAB item? (bug)

### ISSUE THREAD

**Issue by SACavendish** [Minecolonies/minecolonies#94]
### Minecolonies version
0.3.598

### Expected behavior
I wanted to build a baker level 2.
### Actual behaviour
The builder keeps asking me for 'WOODEN SLAB', which I cannot find anywhere, however I have noticed a pink block called 'WOODEN SLAB' in their inventory at some point.
### Steps to reproduce the problem
All I did was upgrade a baker to level 2.

**Comment by Raycoms** [comment]
Please do not place workers which haven't been implemented yet.
They contain blocks from previous minecraft versions which do not exist
anymore.
We will have to rescan these buildings as soon as we implement the workers.

2016-09-04 16:15 GMT-03:00 SACavendish <notifications@github.com>:

**Comment by SACavendish** [comment]
Thank you for your quick response!

**Comment by Raycoms** [comment]
Sometimes he is able to place "oak wood slabs" even if he calls out wooden
slabs, but that doesn't work in all cases, especially when it's from
outdated buildings.

2016-09-04 16:24 GMT-03:00 SACavendish <notifications@github.com>:

**Comment by DanielDingo** [comment]
I have this problem with the townhall. I believe he is meant to be stone slabs because that is all he is missing on the townhall. The top of chimney

**Comment by Raycoms** [comment]
which townhall level?

2016-09-04 23:03 GMT-03:00 DanielDingo <notifications@github.com>:

**Comment by DanielDingo** [comment]
level 1

**Comment by Raycoms** [comment]
just give him oak slabs that should work

2016-09-05 1:07 GMT-03:00 DanielDingo <notifications@github.com>:

**Comment by matthijs186** [comment]
Giving the Builder Oak Wood Slabs for the level 1 Townhall and restarting the server should be a workaround for now.

**Comment by matthijs186** [comment]
I have also come across this in-game (SMP), and I'm positive that [this forum thread](http://www.minecolonies.com/publicforum/m/18051739/viewthread/28238880-problem-townhall-construction) is related.
This probably originates from the outdated townhall from the older Minecraft version, which @Raycoms mentioned above.

Sorry for the closed issue bump, but I thought I'd make things clear since this shouldn't be a problem that you need a workaround for, and I have not seen this issue addressed anywhere else.
